CFLAGS=-Wall -g

all: ex1 ex2 ex3 ex4 ex7 ex8 ex22_main ex24

ex22_main: ex22_main.o ex22.o 

clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 ex22_main ex23 arr enum db ex24
